version: '3'
services: 
  nginx:
    build: 
      context: ./nginx
    ports:
      - 80:80
    links:
      - app
    environment: 
      - APP_HOST_NAME=app
    command: /bin/bash -c "exec nginx -g 'daemon off;'"
  app:
    build:
      context: ./app